// Code generated by options-gen v0.55.5. DO NOT EDIT.

package rolesguardservice

import (
	fmt461e464ebed9 "fmt"

	logger "github.com/assurrussa/goshared/pkg/logger"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	rolesUseCase rolesUseCase,
	permissionUseCase permissionUseCase,
	cache cache,
	logger logger.Logger,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.rolesUseCase = rolesUseCase
	o.permissionUseCase = permissionUseCase
	o.cache = cache
	o.logger = logger

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("rolesUseCase", _validate_Options_rolesUseCase(o)))
	errs.Add(errors461e464ebed9.NewValidationError("permissionUseCase", _validate_Options_permissionUseCase(o)))
	errs.Add(errors461e464ebed9.NewValidationError("cache", _validate_Options_cache(o)))
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	return errs.AsError()
}

func _validate_Options_rolesUseCase(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.rolesUseCase, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `rolesUseCase` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_permissionUseCase(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.permissionUseCase, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `permissionUseCase` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_cache(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.cache, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `cache` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}
