// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/goauth/service/confirmationcodeservice (interfaces: userConfirmationCodeRepository,userConfirmationRepository,notificationService,SubjectConfirmationStore)
//
// Generated by this command:
//
//	mockgen -destination=mocks/service_mock.gen.go -package=confirmationcodeservicemocks . userConfirmationCodeRepository,userConfirmationRepository,notificationService,SubjectConfirmationStore
//

// Package confirmationcodeservicemocks is a generated GoMock package.
package confirmationcodeservicemocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"

	core "github.com/assurrussa/goauth/core"
	notify "github.com/assurrussa/goauth/infrastructure/notify"
	confirmation "github.com/assurrussa/goauth/local/confirmation"
	shared "github.com/assurrussa/goauth/shared"
)

// MockuserConfirmationCodeRepository is a mock of userConfirmationCodeRepository interface.
type MockuserConfirmationCodeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserConfirmationCodeRepositoryMockRecorder
	isgomock struct{}
}

// MockuserConfirmationCodeRepositoryMockRecorder is the mock recorder for MockuserConfirmationCodeRepository.
type MockuserConfirmationCodeRepositoryMockRecorder struct {
	mock *MockuserConfirmationCodeRepository
}

// NewMockuserConfirmationCodeRepository creates a new mock instance.
func NewMockuserConfirmationCodeRepository(ctrl *gomock.Controller) *MockuserConfirmationCodeRepository {
	mock := &MockuserConfirmationCodeRepository{ctrl: ctrl}
	mock.recorder = &MockuserConfirmationCodeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserConfirmationCodeRepository) EXPECT() *MockuserConfirmationCodeRepositoryMockRecorder {
	return m.recorder
}

// CleanupExpiredCodes mocks base method.
func (m *MockuserConfirmationCodeRepository) CleanupExpiredCodes(ctx context.Context, batchSize, minutes int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpiredCodes", ctx, batchSize, minutes)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupExpiredCodes indicates an expected call of CleanupExpiredCodes.
func (mr *MockuserConfirmationCodeRepositoryMockRecorder) CleanupExpiredCodes(ctx, batchSize, minutes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredCodes", reflect.TypeOf((*MockuserConfirmationCodeRepository)(nil).CleanupExpiredCodes), ctx, batchSize, minutes)
}

// CountSince mocks base method.
func (m *MockuserConfirmationCodeRepository) CountSince(ctx context.Context, subjectID shared.SubjectID, targetType confirmation.Type, since time.Time) (confirmation.UsageWindow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSince", ctx, subjectID, targetType, since)
	ret0, _ := ret[0].(confirmation.UsageWindow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSince indicates an expected call of CountSince.
func (mr *MockuserConfirmationCodeRepositoryMockRecorder) CountSince(ctx, subjectID, targetType, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSince", reflect.TypeOf((*MockuserConfirmationCodeRepository)(nil).CountSince), ctx, subjectID, targetType, since)
}

// FindLast mocks base method.
func (m *MockuserConfirmationCodeRepository) FindLast(ctx context.Context, subjectID shared.SubjectID, targetType confirmation.Type) (*confirmation.CodeRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLast", ctx, subjectID, targetType)
	ret0, _ := ret[0].(*confirmation.CodeRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLast indicates an expected call of FindLast.
func (mr *MockuserConfirmationCodeRepositoryMockRecorder) FindLast(ctx, subjectID, targetType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLast", reflect.TypeOf((*MockuserConfirmationCodeRepository)(nil).FindLast), ctx, subjectID, targetType)
}

// GetActiveCodeBySubjectAndType mocks base method.
func (m *MockuserConfirmationCodeRepository) GetActiveCodeBySubjectAndType(ctx context.Context, subjectID shared.SubjectID, codeType confirmation.Type, purpose confirmation.Purpose) (confirmation.CodeRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveCodeBySubjectAndType", ctx, subjectID, codeType, purpose)
	ret0, _ := ret[0].(confirmation.CodeRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveCodeBySubjectAndType indicates an expected call of GetActiveCodeBySubjectAndType.
func (mr *MockuserConfirmationCodeRepositoryMockRecorder) GetActiveCodeBySubjectAndType(ctx, subjectID, codeType, purpose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveCodeBySubjectAndType", reflect.TypeOf((*MockuserConfirmationCodeRepository)(nil).GetActiveCodeBySubjectAndType), ctx, subjectID, codeType, purpose)
}

// IncrementAttempts mocks base method.
func (m *MockuserConfirmationCodeRepository) IncrementAttempts(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAttempts", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementAttempts indicates an expected call of IncrementAttempts.
func (mr *MockuserConfirmationCodeRepositoryMockRecorder) IncrementAttempts(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAttempts", reflect.TypeOf((*MockuserConfirmationCodeRepository)(nil).IncrementAttempts), ctx, id)
}

// UpdateVerified mocks base method.
func (m *MockuserConfirmationCodeRepository) UpdateVerified(ctx context.Context, record confirmation.CodeRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVerified", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVerified indicates an expected call of UpdateVerified.
func (mr *MockuserConfirmationCodeRepositoryMockRecorder) UpdateVerified(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVerified", reflect.TypeOf((*MockuserConfirmationCodeRepository)(nil).UpdateVerified), ctx, record)
}

// UpsertCode mocks base method.
func (m *MockuserConfirmationCodeRepository) UpsertCode(ctx context.Context, record confirmation.CodeRecord) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCode", ctx, record)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertCode indicates an expected call of UpsertCode.
func (mr *MockuserConfirmationCodeRepositoryMockRecorder) UpsertCode(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCode", reflect.TypeOf((*MockuserConfirmationCodeRepository)(nil).UpsertCode), ctx, record)
}

// MockuserConfirmationRepository is a mock of userConfirmationRepository interface.
type MockuserConfirmationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserConfirmationRepositoryMockRecorder
	isgomock struct{}
}

// MockuserConfirmationRepositoryMockRecorder is the mock recorder for MockuserConfirmationRepository.
type MockuserConfirmationRepositoryMockRecorder struct {
	mock *MockuserConfirmationRepository
}

// NewMockuserConfirmationRepository creates a new mock instance.
func NewMockuserConfirmationRepository(ctrl *gomock.Controller) *MockuserConfirmationRepository {
	mock := &MockuserConfirmationRepository{ctrl: ctrl}
	mock.recorder = &MockuserConfirmationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserConfirmationRepository) EXPECT() *MockuserConfirmationRepositoryMockRecorder {
	return m.recorder
}

// GetBySubjectID mocks base method.
func (m *MockuserConfirmationRepository) GetBySubjectID(ctx context.Context, subjectID shared.SubjectID) ([]confirmation.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySubjectID", ctx, subjectID)
	ret0, _ := ret[0].([]confirmation.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySubjectID indicates an expected call of GetBySubjectID.
func (mr *MockuserConfirmationRepositoryMockRecorder) GetBySubjectID(ctx, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySubjectID", reflect.TypeOf((*MockuserConfirmationRepository)(nil).GetBySubjectID), ctx, subjectID)
}

// GetConfirmationStatus mocks base method.
func (m *MockuserConfirmationRepository) GetConfirmationStatus(ctx context.Context, subjectID shared.SubjectID) (confirmation.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfirmationStatus", ctx, subjectID)
	ret0, _ := ret[0].(confirmation.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfirmationStatus indicates an expected call of GetConfirmationStatus.
func (mr *MockuserConfirmationRepositoryMockRecorder) GetConfirmationStatus(ctx, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfirmationStatus", reflect.TypeOf((*MockuserConfirmationRepository)(nil).GetConfirmationStatus), ctx, subjectID)
}

// IsConfirmed mocks base method.
func (m *MockuserConfirmationRepository) IsConfirmed(ctx context.Context, subjectID shared.SubjectID, confirmationType confirmation.Type, purpose confirmation.Purpose) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConfirmed", ctx, subjectID, confirmationType, purpose)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsConfirmed indicates an expected call of IsConfirmed.
func (mr *MockuserConfirmationRepositoryMockRecorder) IsConfirmed(ctx, subjectID, confirmationType, purpose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConfirmed", reflect.TypeOf((*MockuserConfirmationRepository)(nil).IsConfirmed), ctx, subjectID, confirmationType, purpose)
}

// Upsert mocks base method.
func (m *MockuserConfirmationRepository) Upsert(ctx context.Context, record confirmation.Record) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, record)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockuserConfirmationRepositoryMockRecorder) Upsert(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockuserConfirmationRepository)(nil).Upsert), ctx, record)
}

// MocknotificationService is a mock of notificationService interface.
type MocknotificationService struct {
	ctrl     *gomock.Controller
	recorder *MocknotificationServiceMockRecorder
	isgomock struct{}
}

// MocknotificationServiceMockRecorder is the mock recorder for MocknotificationService.
type MocknotificationServiceMockRecorder struct {
	mock *MocknotificationService
}

// NewMocknotificationService creates a new mock instance.
func NewMocknotificationService(ctrl *gomock.Controller) *MocknotificationService {
	mock := &MocknotificationService{ctrl: ctrl}
	mock.recorder = &MocknotificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknotificationService) EXPECT() *MocknotificationServiceMockRecorder {
	return m.recorder
}

// SendToChannel mocks base method.
func (m *MocknotificationService) SendToChannel(ctx context.Context, channel notify.NotificationChannel, notification *notify.Notification, recipients ...*notify.Recipient) ([]*notify.NotificationResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, channel, notification}
	for _, a := range recipients {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendToChannel", varargs...)
	ret0, _ := ret[0].([]*notify.NotificationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendToChannel indicates an expected call of SendToChannel.
func (mr *MocknotificationServiceMockRecorder) SendToChannel(ctx, channel, notification any, recipients ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, channel, notification}, recipients...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendToChannel", reflect.TypeOf((*MocknotificationService)(nil).SendToChannel), varargs...)
}

// MockSubjectConfirmationStore is a mock of SubjectConfirmationStore interface.
type MockSubjectConfirmationStore struct {
	ctrl     *gomock.Controller
	recorder *MockSubjectConfirmationStoreMockRecorder
	isgomock struct{}
}

// MockSubjectConfirmationStoreMockRecorder is the mock recorder for MockSubjectConfirmationStore.
type MockSubjectConfirmationStoreMockRecorder struct {
	mock *MockSubjectConfirmationStore
}

// NewMockSubjectConfirmationStore creates a new mock instance.
func NewMockSubjectConfirmationStore(ctrl *gomock.Controller) *MockSubjectConfirmationStore {
	mock := &MockSubjectConfirmationStore{ctrl: ctrl}
	mock.recorder = &MockSubjectConfirmationStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubjectConfirmationStore) EXPECT() *MockSubjectConfirmationStoreMockRecorder {
	return m.recorder
}

// MarkEmailConfirmed mocks base method.
func (m *MockSubjectConfirmationStore) MarkEmailConfirmed(ctx context.Context, subjectID core.SubjectID, confirmedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEmailConfirmed", ctx, subjectID, confirmedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkEmailConfirmed indicates an expected call of MarkEmailConfirmed.
func (mr *MockSubjectConfirmationStoreMockRecorder) MarkEmailConfirmed(ctx, subjectID, confirmedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEmailConfirmed", reflect.TypeOf((*MockSubjectConfirmationStore)(nil).MarkEmailConfirmed), ctx, subjectID, confirmedAt)
}
