// Code generated by MockGen. DO NOT EDIT.
// Source: mocks.go
//
// Generated by this command:
//
//	mockgen -source=mocks.go -destination=mocks.gen.go -package=testsupport
//

// Package testsupport is a generated GoMock package.
package testsupport

import (
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"

	outbox "github.com/assurrussa/goauth/infrastructure/outbox"
)

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// ReadCommitted mocks base method.
func (m *MockTxManager) ReadCommitted(ctx context.Context, accessMode pgx.TxAccessMode, fn outbox.StoragePgsqlFnCallback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCommitted", ctx, accessMode, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReadCommitted indicates an expected call of ReadCommitted.
func (mr *MockTxManagerMockRecorder) ReadCommitted(ctx, accessMode, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCommitted", reflect.TypeOf((*MockTxManager)(nil).ReadCommitted), ctx, accessMode, fn)
}

// RepeatableRead mocks base method.
func (m *MockTxManager) RepeatableRead(ctx context.Context, accessMode pgx.TxAccessMode, fn outbox.StoragePgsqlFnCallback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepeatableRead", ctx, accessMode, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RepeatableRead indicates an expected call of RepeatableRead.
func (mr *MockTxManagerMockRecorder) RepeatableRead(ctx, accessMode, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepeatableRead", reflect.TypeOf((*MockTxManager)(nil).RepeatableRead), ctx, accessMode, fn)
}

// RunInTx mocks base method.
func (m *MockTxManager) RunInTx(ctx context.Context, f func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MockTxManagerMockRecorder) RunInTx(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*MockTxManager)(nil).RunInTx), ctx, f)
}

// Serializable mocks base method.
func (m *MockTxManager) Serializable(ctx context.Context, accessMode pgx.TxAccessMode, fn outbox.StoragePgsqlFnCallback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Serializable", ctx, accessMode, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Serializable indicates an expected call of Serializable.
func (mr *MockTxManagerMockRecorder) Serializable(ctx, accessMode, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serializable", reflect.TypeOf((*MockTxManager)(nil).Serializable), ctx, accessMode, fn)
}
