// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository_mock.gen.go -package=repositorymocks
//

// Package repositorymocks is a generated GoMock package.
package repositorymocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	model "github.com/assurrussa/goauth/internal/legacy/domain/roles/model"
	repository "github.com/assurrussa/goauth/internal/legacy/domain/roles/repository"
	shared "github.com/assurrussa/goauth/internal/legacy/domain/roles/shared"
)

// MockRoleRepository is a mock of RoleRepository interface.
type MockRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepositoryMockRecorder
	isgomock struct{}
}

// MockRoleRepositoryMockRecorder is the mock recorder for MockRoleRepository.
type MockRoleRepositoryMockRecorder struct {
	mock *MockRoleRepository
}

// NewMockRoleRepository creates a new mock instance.
func NewMockRoleRepository(ctrl *gomock.Controller) *MockRoleRepository {
	mock := &MockRoleRepository{ctrl: ctrl}
	mock.recorder = &MockRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepository) EXPECT() *MockRoleRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoleRepository) Create(ctx context.Context, input model.Role) (*model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRoleRepositoryMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoleRepository)(nil).Create), ctx, input)
}

// Delete mocks base method.
func (m *MockRoleRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRoleRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoleRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockRoleRepository) GetByID(ctx context.Context, id int64) (*model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRoleRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRoleRepository)(nil).GetByID), ctx, id)
}

// GetBySlug mocks base method.
func (m *MockRoleRepository) GetBySlug(ctx context.Context, slug string) (*model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", ctx, slug)
	ret0, _ := ret[0].(*model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockRoleRepositoryMockRecorder) GetBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockRoleRepository)(nil).GetBySlug), ctx, slug)
}

// List mocks base method.
func (m *MockRoleRepository) List(ctx context.Context, filter repository.RoleFilter) ([]model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRoleRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRoleRepository)(nil).List), ctx, filter)
}

// ListAllRolePermissions mocks base method.
func (m *MockRoleRepository) ListAllRolePermissions(ctx context.Context) ([]model.RolePermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllRolePermissions", ctx)
	ret0, _ := ret[0].([]model.RolePermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllRolePermissions indicates an expected call of ListAllRolePermissions.
func (mr *MockRoleRepositoryMockRecorder) ListAllRolePermissions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllRolePermissions", reflect.TypeOf((*MockRoleRepository)(nil).ListAllRolePermissions), ctx)
}

// ListAllSubjectRoles mocks base method.
func (m *MockRoleRepository) ListAllSubjectRoles(ctx context.Context) ([]model.SubjectRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllSubjectRoles", ctx)
	ret0, _ := ret[0].([]model.SubjectRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllSubjectRoles indicates an expected call of ListAllSubjectRoles.
func (mr *MockRoleRepositoryMockRecorder) ListAllSubjectRoles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllSubjectRoles", reflect.TypeOf((*MockRoleRepository)(nil).ListAllSubjectRoles), ctx)
}

// Update mocks base method.
func (m *MockRoleRepository) Update(ctx context.Context, input model.Role) (*model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, input)
	ret0, _ := ret[0].(*model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRoleRepositoryMockRecorder) Update(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoleRepository)(nil).Update), ctx, input)
}

// MockPermissionRepository is a mock of PermissionRepository interface.
type MockPermissionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionRepositoryMockRecorder
	isgomock struct{}
}

// MockPermissionRepositoryMockRecorder is the mock recorder for MockPermissionRepository.
type MockPermissionRepositoryMockRecorder struct {
	mock *MockPermissionRepository
}

// NewMockPermissionRepository creates a new mock instance.
func NewMockPermissionRepository(ctrl *gomock.Controller) *MockPermissionRepository {
	mock := &MockPermissionRepository{ctrl: ctrl}
	mock.recorder = &MockPermissionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionRepository) EXPECT() *MockPermissionRepositoryMockRecorder {
	return m.recorder
}

// CreateBulk mocks base method.
func (m *MockPermissionRepository) CreateBulk(ctx context.Context, inputs []model.Permission) ([]model.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBulk", ctx, inputs)
	ret0, _ := ret[0].([]model.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBulk indicates an expected call of CreateBulk.
func (mr *MockPermissionRepositoryMockRecorder) CreateBulk(ctx, inputs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBulk", reflect.TypeOf((*MockPermissionRepository)(nil).CreateBulk), ctx, inputs)
}

// GetByKey mocks base method.
func (m *MockPermissionRepository) GetByKey(ctx context.Context, key shared.PermissionKey) (*model.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKey", ctx, key)
	ret0, _ := ret[0].(*model.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByKey indicates an expected call of GetByKey.
func (mr *MockPermissionRepositoryMockRecorder) GetByKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKey", reflect.TypeOf((*MockPermissionRepository)(nil).GetByKey), ctx, key)
}

// GetByUUID mocks base method.
func (m *MockPermissionRepository) GetByUUID(ctx context.Context, uuid string) (*model.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", ctx, uuid)
	ret0, _ := ret[0].(*model.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID.
func (mr *MockPermissionRepositoryMockRecorder) GetByUUID(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockPermissionRepository)(nil).GetByUUID), ctx, uuid)
}

// ListAllPermissions mocks base method.
func (m *MockPermissionRepository) ListAllPermissions(ctx context.Context) ([]model.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllPermissions", ctx)
	ret0, _ := ret[0].([]model.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllPermissions indicates an expected call of ListAllPermissions.
func (mr *MockPermissionRepositoryMockRecorder) ListAllPermissions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllPermissions", reflect.TypeOf((*MockPermissionRepository)(nil).ListAllPermissions), ctx)
}

// ListAllPermissionsByRoles mocks base method.
func (m *MockPermissionRepository) ListAllPermissionsByRoles(ctx context.Context, roleIDs []int64) ([]model.PermissionWithRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllPermissionsByRoles", ctx, roleIDs)
	ret0, _ := ret[0].([]model.PermissionWithRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllPermissionsByRoles indicates an expected call of ListAllPermissionsByRoles.
func (mr *MockPermissionRepositoryMockRecorder) ListAllPermissionsByRoles(ctx, roleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllPermissionsByRoles", reflect.TypeOf((*MockPermissionRepository)(nil).ListAllPermissionsByRoles), ctx, roleIDs)
}

// ListByFilter mocks base method.
func (m *MockPermissionRepository) ListByFilter(ctx context.Context, filter repository.PermissionFilter) ([]model.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByFilter", ctx, filter)
	ret0, _ := ret[0].([]model.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByFilter indicates an expected call of ListByFilter.
func (mr *MockPermissionRepositoryMockRecorder) ListByFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByFilter", reflect.TypeOf((*MockPermissionRepository)(nil).ListByFilter), ctx, filter)
}

// MockAssignmentRepository is a mock of AssignmentRepository interface.
type MockAssignmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAssignmentRepositoryMockRecorder
	isgomock struct{}
}

// MockAssignmentRepositoryMockRecorder is the mock recorder for MockAssignmentRepository.
type MockAssignmentRepositoryMockRecorder struct {
	mock *MockAssignmentRepository
}

// NewMockAssignmentRepository creates a new mock instance.
func NewMockAssignmentRepository(ctrl *gomock.Controller) *MockAssignmentRepository {
	mock := &MockAssignmentRepository{ctrl: ctrl}
	mock.recorder = &MockAssignmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssignmentRepository) EXPECT() *MockAssignmentRepositoryMockRecorder {
	return m.recorder
}

// AssignRoleToSubject mocks base method.
func (m *MockAssignmentRepository) AssignRoleToSubject(ctx context.Context, subjectID string, roleIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRoleToSubject", ctx, subjectID, roleIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRoleToSubject indicates an expected call of AssignRoleToSubject.
func (mr *MockAssignmentRepositoryMockRecorder) AssignRoleToSubject(ctx, subjectID, roleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRoleToSubject", reflect.TypeOf((*MockAssignmentRepository)(nil).AssignRoleToSubject), ctx, subjectID, roleIDs)
}

// ListPermissions mocks base method.
func (m *MockAssignmentRepository) ListPermissions(ctx context.Context, roleID int64) ([]model.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPermissions", ctx, roleID)
	ret0, _ := ret[0].([]model.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPermissions indicates an expected call of ListPermissions.
func (mr *MockAssignmentRepositoryMockRecorder) ListPermissions(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPermissions", reflect.TypeOf((*MockAssignmentRepository)(nil).ListPermissions), ctx, roleID)
}

// ListSubjectRoles mocks base method.
func (m *MockAssignmentRepository) ListSubjectRoles(ctx context.Context, subjectID string) ([]model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubjectRoles", ctx, subjectID)
	ret0, _ := ret[0].([]model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubjectRoles indicates an expected call of ListSubjectRoles.
func (mr *MockAssignmentRepositoryMockRecorder) ListSubjectRoles(ctx, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubjectRoles", reflect.TypeOf((*MockAssignmentRepository)(nil).ListSubjectRoles), ctx, subjectID)
}

// ReplacePermissions mocks base method.
func (m *MockAssignmentRepository) ReplacePermissions(ctx context.Context, roleID int64, permissionIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplacePermissions", ctx, roleID, permissionIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplacePermissions indicates an expected call of ReplacePermissions.
func (mr *MockAssignmentRepositoryMockRecorder) ReplacePermissions(ctx, roleID, permissionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplacePermissions", reflect.TypeOf((*MockAssignmentRepository)(nil).ReplacePermissions), ctx, roleID, permissionIDs)
}

// MockHierarchyRepository is a mock of HierarchyRepository interface.
type MockHierarchyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHierarchyRepositoryMockRecorder
	isgomock struct{}
}

// MockHierarchyRepositoryMockRecorder is the mock recorder for MockHierarchyRepository.
type MockHierarchyRepositoryMockRecorder struct {
	mock *MockHierarchyRepository
}

// NewMockHierarchyRepository creates a new mock instance.
func NewMockHierarchyRepository(ctrl *gomock.Controller) *MockHierarchyRepository {
	mock := &MockHierarchyRepository{ctrl: ctrl}
	mock.recorder = &MockHierarchyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHierarchyRepository) EXPECT() *MockHierarchyRepositoryMockRecorder {
	return m.recorder
}

// ListAllRoleHierarchy mocks base method.
func (m *MockHierarchyRepository) ListAllRoleHierarchy(ctx context.Context) ([]model.RoleHierarchy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllRoleHierarchy", ctx)
	ret0, _ := ret[0].([]model.RoleHierarchy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllRoleHierarchy indicates an expected call of ListAllRoleHierarchy.
func (mr *MockHierarchyRepositoryMockRecorder) ListAllRoleHierarchy(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllRoleHierarchy", reflect.TypeOf((*MockHierarchyRepository)(nil).ListAllRoleHierarchy), ctx)
}

// ListChildren mocks base method.
func (m *MockHierarchyRepository) ListChildren(ctx context.Context, parentRoleID int64) ([]model.RoleHierarchy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChildren", ctx, parentRoleID)
	ret0, _ := ret[0].([]model.RoleHierarchy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChildren indicates an expected call of ListChildren.
func (mr *MockHierarchyRepositoryMockRecorder) ListChildren(ctx, parentRoleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChildren", reflect.TypeOf((*MockHierarchyRepository)(nil).ListChildren), ctx, parentRoleID)
}

// ListParents mocks base method.
func (m *MockHierarchyRepository) ListParents(ctx context.Context, childRoleID int64) ([]model.RoleHierarchy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListParents", ctx, childRoleID)
	ret0, _ := ret[0].([]model.RoleHierarchy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListParents indicates an expected call of ListParents.
func (mr *MockHierarchyRepositoryMockRecorder) ListParents(ctx, childRoleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListParents", reflect.TypeOf((*MockHierarchyRepository)(nil).ListParents), ctx, childRoleID)
}

// SetParent mocks base method.
func (m *MockHierarchyRepository) SetParent(ctx context.Context, childRoleID int64, parentRoleID *int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetParent", ctx, childRoleID, parentRoleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetParent indicates an expected call of SetParent.
func (mr *MockHierarchyRepositoryMockRecorder) SetParent(ctx, childRoleID, parentRoleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetParent", reflect.TypeOf((*MockHierarchyRepository)(nil).SetParent), ctx, childRoleID, parentRoleID)
}
