// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/goauth/internal/legacy/domain/roles/service/guard (interfaces: rolesUseCase,permissionUseCase,cache)
//
// Generated by this command:
//
//	mockgen -destination=mocks/service_mock.gen.go -package=rolesguardservicemocks . rolesUseCase,permissionUseCase,cache
//

// Package rolesguardservicemocks is a generated GoMock package.
package rolesguardservicemocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	model "github.com/assurrussa/goauth/internal/legacy/domain/roles/model"
	shared "github.com/assurrussa/goauth/internal/legacy/domain/roles/shared"
	listsubjectroles "github.com/assurrussa/goauth/internal/legacy/domain/roles/usecases/query/list_subject_roles"
)

// MockrolesUseCase is a mock of rolesUseCase interface.
type MockrolesUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockrolesUseCaseMockRecorder
	isgomock struct{}
}

// MockrolesUseCaseMockRecorder is the mock recorder for MockrolesUseCase.
type MockrolesUseCaseMockRecorder struct {
	mock *MockrolesUseCase
}

// NewMockrolesUseCase creates a new mock instance.
func NewMockrolesUseCase(ctrl *gomock.Controller) *MockrolesUseCase {
	mock := &MockrolesUseCase{ctrl: ctrl}
	mock.recorder = &MockrolesUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrolesUseCase) EXPECT() *MockrolesUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockrolesUseCase) Handle(ctx context.Context, req listsubjectroles.Request) (listsubjectroles.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(listsubjectroles.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockrolesUseCaseMockRecorder) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockrolesUseCase)(nil).Handle), ctx, req)
}

// MockpermissionUseCase is a mock of permissionUseCase interface.
type MockpermissionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockpermissionUseCaseMockRecorder
	isgomock struct{}
}

// MockpermissionUseCaseMockRecorder is the mock recorder for MockpermissionUseCase.
type MockpermissionUseCaseMockRecorder struct {
	mock *MockpermissionUseCase
}

// NewMockpermissionUseCase creates a new mock instance.
func NewMockpermissionUseCase(ctrl *gomock.Controller) *MockpermissionUseCase {
	mock := &MockpermissionUseCase{ctrl: ctrl}
	mock.recorder = &MockpermissionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpermissionUseCase) EXPECT() *MockpermissionUseCaseMockRecorder {
	return m.recorder
}

// HasPermission mocks base method.
func (m *MockpermissionUseCase) HasPermission(ctx context.Context, subjectID string, key shared.PermissionKey) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPermission", ctx, subjectID, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPermission indicates an expected call of HasPermission.
func (mr *MockpermissionUseCaseMockRecorder) HasPermission(ctx, subjectID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPermission", reflect.TypeOf((*MockpermissionUseCase)(nil).HasPermission), ctx, subjectID, key)
}

// ListAllPermissionsByRoles mocks base method.
func (m *MockpermissionUseCase) ListAllPermissionsByRoles(ctx context.Context, roleIDs []int64) ([]model.PermissionWithRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllPermissionsByRoles", ctx, roleIDs)
	ret0, _ := ret[0].([]model.PermissionWithRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllPermissionsByRoles indicates an expected call of ListAllPermissionsByRoles.
func (mr *MockpermissionUseCaseMockRecorder) ListAllPermissionsByRoles(ctx, roleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllPermissionsByRoles", reflect.TypeOf((*MockpermissionUseCase)(nil).ListAllPermissionsByRoles), ctx, roleIDs)
}

// Mockcache is a mock of cache interface.
type Mockcache struct {
	ctrl     *gomock.Controller
	recorder *MockcacheMockRecorder
	isgomock struct{}
}

// MockcacheMockRecorder is the mock recorder for Mockcache.
type MockcacheMockRecorder struct {
	mock *Mockcache
}

// NewMockcache creates a new mock instance.
func NewMockcache(ctrl *gomock.Controller) *Mockcache {
	mock := &Mockcache{ctrl: ctrl}
	mock.recorder = &MockcacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcache) EXPECT() *MockcacheMockRecorder {
	return m.recorder
}

// AllRolePermissions mocks base method.
func (m *Mockcache) AllRolePermissions(roles []model.Role) map[int64]map[int64]model.Permission {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllRolePermissions", roles)
	ret0, _ := ret[0].(map[int64]map[int64]model.Permission)
	return ret0
}

// AllRolePermissions indicates an expected call of AllRolePermissions.
func (mr *MockcacheMockRecorder) AllRolePermissions(roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllRolePermissions", reflect.TypeOf((*Mockcache)(nil).AllRolePermissions), roles)
}

// Enabled mocks base method.
func (m *Mockcache) Enabled(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enabled", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enabled indicates an expected call of Enabled.
func (mr *MockcacheMockRecorder) Enabled(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enabled", reflect.TypeOf((*Mockcache)(nil).Enabled), ctx)
}

// SubjectRoles mocks base method.
func (m *Mockcache) SubjectRoles(subjectID string) []model.Role {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubjectRoles", subjectID)
	ret0, _ := ret[0].([]model.Role)
	return ret0
}

// SubjectRoles indicates an expected call of SubjectRoles.
func (mr *MockcacheMockRecorder) SubjectRoles(subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubjectRoles", reflect.TypeOf((*Mockcache)(nil).SubjectRoles), subjectID)
}
