// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/goauth/internal/legacy/usecases/command/user_register (interfaces: authService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/usecase_mock.gen.go -package=userregistermocks . authService
//

// Package userregistermocks is a generated GoMock package.
package userregistermocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	core "github.com/assurrussa/goauth/internal/legacy/core"
)

// MockauthService is a mock of authService interface.
type MockauthService struct {
	ctrl     *gomock.Controller
	recorder *MockauthServiceMockRecorder
	isgomock struct{}
}

// MockauthServiceMockRecorder is the mock recorder for MockauthService.
type MockauthServiceMockRecorder struct {
	mock *MockauthService
}

// NewMockauthService creates a new mock instance.
func NewMockauthService(ctrl *gomock.Controller) *MockauthService {
	mock := &MockauthService{ctrl: ctrl}
	mock.recorder = &MockauthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthService) EXPECT() *MockauthServiceMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockauthService) Register(ctx context.Context, email, password, confirmPassword, name string) (core.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, email, password, confirmPassword, name)
	ret0, _ := ret[0].(core.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockauthServiceMockRecorder) Register(ctx, email, password, confirmPassword, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockauthService)(nil).Register), ctx, email, password, confirmPassword, name)
}
