// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/goauth/internal/legacy/service/userconfirmationservice (interfaces: userConfirmationRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/service_mock.gen.go -package=userconfirmationservicemocks . userConfirmationRepository
//

// Package userconfirmationservicemocks is a generated GoMock package.
package userconfirmationservicemocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	core "github.com/assurrussa/goauth/internal/legacy/core"
	confirmation "github.com/assurrussa/goauth/internal/legacy/local/confirmation"
)

// MockuserConfirmationRepository is a mock of userConfirmationRepository interface.
type MockuserConfirmationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserConfirmationRepositoryMockRecorder
	isgomock struct{}
}

// MockuserConfirmationRepositoryMockRecorder is the mock recorder for MockuserConfirmationRepository.
type MockuserConfirmationRepositoryMockRecorder struct {
	mock *MockuserConfirmationRepository
}

// NewMockuserConfirmationRepository creates a new mock instance.
func NewMockuserConfirmationRepository(ctrl *gomock.Controller) *MockuserConfirmationRepository {
	mock := &MockuserConfirmationRepository{ctrl: ctrl}
	mock.recorder = &MockuserConfirmationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserConfirmationRepository) EXPECT() *MockuserConfirmationRepositoryMockRecorder {
	return m.recorder
}

// GetBySubjectID mocks base method.
func (m *MockuserConfirmationRepository) GetBySubjectID(ctx context.Context, subjectID core.SubjectID) ([]confirmation.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySubjectID", ctx, subjectID)
	ret0, _ := ret[0].([]confirmation.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySubjectID indicates an expected call of GetBySubjectID.
func (mr *MockuserConfirmationRepositoryMockRecorder) GetBySubjectID(ctx, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySubjectID", reflect.TypeOf((*MockuserConfirmationRepository)(nil).GetBySubjectID), ctx, subjectID)
}

// GetConfirmationStatus mocks base method.
func (m *MockuserConfirmationRepository) GetConfirmationStatus(ctx context.Context, subjectID core.SubjectID) (confirmation.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfirmationStatus", ctx, subjectID)
	ret0, _ := ret[0].(confirmation.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfirmationStatus indicates an expected call of GetConfirmationStatus.
func (mr *MockuserConfirmationRepositoryMockRecorder) GetConfirmationStatus(ctx, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfirmationStatus", reflect.TypeOf((*MockuserConfirmationRepository)(nil).GetConfirmationStatus), ctx, subjectID)
}

// IsConfirmed mocks base method.
func (m *MockuserConfirmationRepository) IsConfirmed(ctx context.Context, subjectID core.SubjectID, confirmationType confirmation.Type, purpose confirmation.Purpose) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConfirmed", ctx, subjectID, confirmationType, purpose)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsConfirmed indicates an expected call of IsConfirmed.
func (mr *MockuserConfirmationRepositoryMockRecorder) IsConfirmed(ctx, subjectID, confirmationType, purpose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConfirmed", reflect.TypeOf((*MockuserConfirmationRepository)(nil).IsConfirmed), ctx, subjectID, confirmationType, purpose)
}
