// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/goauth/internal/legacy/usecases/query/user_auth_me (interfaces: subjectLookup,profileLookup,repoToken)
//
// Generated by this command:
//
//	mockgen -destination=mocks/usecase_mock.gen.go -package=userauthmemocks . subjectLookup,profileLookup,repoToken
//

// Package userauthmemocks is a generated GoMock package.
package userauthmemocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	core "github.com/assurrussa/goauth/internal/legacy/core"
)

// MocksubjectLookup is a mock of subjectLookup interface.
type MocksubjectLookup struct {
	ctrl     *gomock.Controller
	recorder *MocksubjectLookupMockRecorder
	isgomock struct{}
}

// MocksubjectLookupMockRecorder is the mock recorder for MocksubjectLookup.
type MocksubjectLookupMockRecorder struct {
	mock *MocksubjectLookup
}

// NewMocksubjectLookup creates a new mock instance.
func NewMocksubjectLookup(ctrl *gomock.Controller) *MocksubjectLookup {
	mock := &MocksubjectLookup{ctrl: ctrl}
	mock.recorder = &MocksubjectLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksubjectLookup) EXPECT() *MocksubjectLookupMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MocksubjectLookup) GetByID(ctx context.Context, subjectID core.SubjectID) (core.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, subjectID)
	ret0, _ := ret[0].(core.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MocksubjectLookupMockRecorder) GetByID(ctx, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MocksubjectLookup)(nil).GetByID), ctx, subjectID)
}

// MockprofileLookup is a mock of profileLookup interface.
type MockprofileLookup struct {
	ctrl     *gomock.Controller
	recorder *MockprofileLookupMockRecorder
	isgomock struct{}
}

// MockprofileLookupMockRecorder is the mock recorder for MockprofileLookup.
type MockprofileLookupMockRecorder struct {
	mock *MockprofileLookup
}

// NewMockprofileLookup creates a new mock instance.
func NewMockprofileLookup(ctrl *gomock.Controller) *MockprofileLookup {
	mock := &MockprofileLookup{ctrl: ctrl}
	mock.recorder = &MockprofileLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprofileLookup) EXPECT() *MockprofileLookupMockRecorder {
	return m.recorder
}

// GetBySubjectID mocks base method.
func (m *MockprofileLookup) GetBySubjectID(ctx context.Context, subjectID core.SubjectID) (core.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySubjectID", ctx, subjectID)
	ret0, _ := ret[0].(core.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySubjectID indicates an expected call of GetBySubjectID.
func (mr *MockprofileLookupMockRecorder) GetBySubjectID(ctx, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySubjectID", reflect.TypeOf((*MockprofileLookup)(nil).GetBySubjectID), ctx, subjectID)
}

// MockrepoToken is a mock of repoToken interface.
type MockrepoToken struct {
	ctrl     *gomock.Controller
	recorder *MockrepoTokenMockRecorder
	isgomock struct{}
}

// MockrepoTokenMockRecorder is the mock recorder for MockrepoToken.
type MockrepoTokenMockRecorder struct {
	mock *MockrepoToken
}

// NewMockrepoToken creates a new mock instance.
func NewMockrepoToken(ctrl *gomock.Controller) *MockrepoToken {
	mock := &MockrepoToken{ctrl: ctrl}
	mock.recorder = &MockrepoTokenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrepoToken) EXPECT() *MockrepoTokenMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockrepoToken) Delete(ctx context.Context, subjectID core.SubjectID, token string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, subjectID, token)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockrepoTokenMockRecorder) Delete(ctx, subjectID, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockrepoToken)(nil).Delete), ctx, subjectID, token)
}
