// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/goauth/internal/legacy/usecases/query/user_token_list (interfaces: authService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/usecase_mock.gen.go -package=usertokenlistmocks . authService
//

// Package usertokenlistmocks is a generated GoMock package.
package usertokenlistmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	core "github.com/assurrussa/goauth/internal/legacy/core"
	authjwtservice "github.com/assurrussa/goauth/internal/legacy/service/authjwtservice"
)

// MockauthService is a mock of authService interface.
type MockauthService struct {
	ctrl     *gomock.Controller
	recorder *MockauthServiceMockRecorder
	isgomock struct{}
}

// MockauthServiceMockRecorder is the mock recorder for MockauthService.
type MockauthServiceMockRecorder struct {
	mock *MockauthService
}

// NewMockauthService creates a new mock instance.
func NewMockauthService(ctrl *gomock.Controller) *MockauthService {
	mock := &MockauthService{ctrl: ctrl}
	mock.recorder = &MockauthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthService) EXPECT() *MockauthServiceMockRecorder {
	return m.recorder
}

// GetUserTokens mocks base method.
func (m *MockauthService) GetUserTokens(ctx context.Context, subjectID core.SubjectID, currentToken string) ([]authjwtservice.TokenInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTokens", ctx, subjectID, currentToken)
	ret0, _ := ret[0].([]authjwtservice.TokenInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTokens indicates an expected call of GetUserTokens.
func (mr *MockauthServiceMockRecorder) GetUserTokens(ctx, subjectID, currentToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTokens", reflect.TypeOf((*MockauthService)(nil).GetUserTokens), ctx, subjectID, currentToken)
}
