// Code generated by options-gen v0.55.3. DO NOT EDIT.

package userconfirmationservice

import (
	fmt461e464ebed9 "fmt"

	"github.com/assurrussa/goshared/pkg/logger"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	logger logger.Logger,
	userConfirmationRepo userConfirmationRepository,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.logger = logger
	o.userConfirmationRepo = userConfirmationRepo

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	errs.Add(errors461e464ebed9.NewValidationError("userConfirmationRepo", _validate_Options_userConfirmationRepo(o)))
	return errs.AsError()
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_userConfirmationRepo(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.userConfirmationRepo, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `userConfirmationRepo` did not pass the test: %w", err)
	}
	return nil
}
