// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/usecase_mock.gen.go -package=listallrolesmocks
//

// Package listallrolesmocks is a generated GoMock package.
package listallrolesmocks

import (
	context "context"
	reflect "reflect"

	model "github.com/assurrussa/goauth/domain/roles/model"
	repository "github.com/assurrussa/goauth/domain/roles/repository"
	gomock "go.uber.org/mock/gomock"
)

// Mockservice is a mock of service interface.
type Mockservice struct {
	ctrl     *gomock.Controller
	recorder *MockserviceMockRecorder
	isgomock struct{}
}

// MockserviceMockRecorder is the mock recorder for Mockservice.
type MockserviceMockRecorder struct {
	mock *Mockservice
}

// NewMockservice creates a new mock instance.
func NewMockservice(ctrl *gomock.Controller) *Mockservice {
	mock := &Mockservice{ctrl: ctrl}
	mock.recorder = &MockserviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockservice) EXPECT() *MockserviceMockRecorder {
	return m.recorder
}

// ListRolePermissions mocks base method.
func (m *Mockservice) ListRolePermissions(ctx context.Context, roleID int64) ([]model.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRolePermissions", ctx, roleID)
	ret0, _ := ret[0].([]model.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRolePermissions indicates an expected call of ListRolePermissions.
func (mr *MockserviceMockRecorder) ListRolePermissions(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRolePermissions", reflect.TypeOf((*Mockservice)(nil).ListRolePermissions), ctx, roleID)
}

// ListRoles mocks base method.
func (m *Mockservice) ListRoles(ctx context.Context, filter repository.RoleFilter) ([]model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", ctx, filter)
	ret0, _ := ret[0].([]model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockserviceMockRecorder) ListRoles(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*Mockservice)(nil).ListRoles), ctx, filter)
}

// MockroleRepository is a mock of roleRepository interface.
type MockroleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockroleRepositoryMockRecorder
	isgomock struct{}
}

// MockroleRepositoryMockRecorder is the mock recorder for MockroleRepository.
type MockroleRepositoryMockRecorder struct {
	mock *MockroleRepository
}

// NewMockroleRepository creates a new mock instance.
func NewMockroleRepository(ctrl *gomock.Controller) *MockroleRepository {
	mock := &MockroleRepository{ctrl: ctrl}
	mock.recorder = &MockroleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockroleRepository) EXPECT() *MockroleRepositoryMockRecorder {
	return m.recorder
}

// ListAllSubjectRoles mocks base method.
func (m *MockroleRepository) ListAllSubjectRoles(ctx context.Context) ([]model.SubjectRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllSubjectRoles", ctx)
	ret0, _ := ret[0].([]model.SubjectRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllSubjectRoles indicates an expected call of ListAllSubjectRoles.
func (mr *MockroleRepositoryMockRecorder) ListAllSubjectRoles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllSubjectRoles", reflect.TypeOf((*MockroleRepository)(nil).ListAllSubjectRoles), ctx)
}

// ListAllRolePermissions mocks base method.
func (m *MockroleRepository) ListAllRolePermissions(ctx context.Context) ([]model.RolePermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllRolePermissions", ctx)
	ret0, _ := ret[0].([]model.RolePermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllRolePermissions indicates an expected call of ListAllRolePermissions.
func (mr *MockroleRepositoryMockRecorder) ListAllRolePermissions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllRolePermissions", reflect.TypeOf((*MockroleRepository)(nil).ListAllRolePermissions), ctx)
}

// MockpermissionRepository is a mock of permissionRepository interface.
type MockpermissionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockpermissionRepositoryMockRecorder
	isgomock struct{}
}

// MockpermissionRepositoryMockRecorder is the mock recorder for MockpermissionRepository.
type MockpermissionRepositoryMockRecorder struct {
	mock *MockpermissionRepository
}

// NewMockpermissionRepository creates a new mock instance.
func NewMockpermissionRepository(ctrl *gomock.Controller) *MockpermissionRepository {
	mock := &MockpermissionRepository{ctrl: ctrl}
	mock.recorder = &MockpermissionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpermissionRepository) EXPECT() *MockpermissionRepositoryMockRecorder {
	return m.recorder
}

// ListAllPermissions mocks base method.
func (m *MockpermissionRepository) ListAllPermissions(ctx context.Context) ([]model.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllPermissions", ctx)
	ret0, _ := ret[0].([]model.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllPermissions indicates an expected call of ListAllPermissions.
func (mr *MockpermissionRepositoryMockRecorder) ListAllPermissions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllPermissions", reflect.TypeOf((*MockpermissionRepository)(nil).ListAllPermissions), ctx)
}

// MockassignmentRepository is a mock of assignmentRepository interface.
type MockassignmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockassignmentRepositoryMockRecorder
	isgomock struct{}
}

// MockassignmentRepositoryMockRecorder is the mock recorder for MockassignmentRepository.
type MockassignmentRepositoryMockRecorder struct {
	mock *MockassignmentRepository
}

// NewMockassignmentRepository creates a new mock instance.
func NewMockassignmentRepository(ctrl *gomock.Controller) *MockassignmentRepository {
	mock := &MockassignmentRepository{ctrl: ctrl}
	mock.recorder = &MockassignmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockassignmentRepository) EXPECT() *MockassignmentRepositoryMockRecorder {
	return m.recorder
}

// ListSubjectRoles mocks base method.
func (m *MockassignmentRepository) ListSubjectRoles(ctx context.Context, subjectID string) ([]model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubjectRoles", ctx, subjectID)
	ret0, _ := ret[0].([]model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubjectRoles indicates an expected call of ListSubjectRoles.
func (mr *MockassignmentRepositoryMockRecorder) ListSubjectRoles(ctx, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubjectRoles", reflect.TypeOf((*MockassignmentRepository)(nil).ListSubjectRoles), ctx, subjectID)
}

// MockhierarchyRepository is a mock of hierarchyRepository interface.
type MockhierarchyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockhierarchyRepositoryMockRecorder
	isgomock struct{}
}

// MockhierarchyRepositoryMockRecorder is the mock recorder for MockhierarchyRepository.
type MockhierarchyRepositoryMockRecorder struct {
	mock *MockhierarchyRepository
}

// NewMockhierarchyRepository creates a new mock instance.
func NewMockhierarchyRepository(ctrl *gomock.Controller) *MockhierarchyRepository {
	mock := &MockhierarchyRepository{ctrl: ctrl}
	mock.recorder = &MockhierarchyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhierarchyRepository) EXPECT() *MockhierarchyRepositoryMockRecorder {
	return m.recorder
}

// ListAllRoleHierarchy mocks base method.
func (m *MockhierarchyRepository) ListAllRoleHierarchy(ctx context.Context) ([]model.RoleHierarchy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllRoleHierarchy", ctx)
	ret0, _ := ret[0].([]model.RoleHierarchy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllRoleHierarchy indicates an expected call of ListAllRoleHierarchy.
func (mr *MockhierarchyRepositoryMockRecorder) ListAllRoleHierarchy(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllRoleHierarchy", reflect.TypeOf((*MockhierarchyRepository)(nil).ListAllRoleHierarchy), ctx)
}
