// Code generated by options-gen v0.55.3. DO NOT EDIT.

package sendconfirmationcode

import (
	fmt461e464ebed9 "fmt"

	logger3 "github.com/assurrussa/gologger"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"

	outbox "github.com/assurrussa/goauth/internal/legacy/infrastructure/outbox"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	logger logger3.Logger,
	confirmationService confirmationService,
	profiles profileLookup,
	trx outbox.StoragePgsqlTxManager,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.logger = logger
	o.confirmationService = confirmationService
	o.profiles = profiles
	o.trx = trx

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	errs.Add(errors461e464ebed9.NewValidationError("confirmationService", _validate_Options_confirmationService(o)))
	errs.Add(errors461e464ebed9.NewValidationError("profiles", _validate_Options_profiles(o)))
	errs.Add(errors461e464ebed9.NewValidationError("trx", _validate_Options_trx(o)))
	return errs.AsError()
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_confirmationService(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.confirmationService, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `confirmationService` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_profiles(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.profiles, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `profiles` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_trx(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.trx, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `trx` did not pass the test: %w", err)
	}
	return nil
}
