// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/goauth/internal/legacy/usecases/command/user_token_ban (interfaces: authService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/usecase_mock.gen.go -package=usertokenbanmocks . authService
//

// Package usertokenbanmocks is a generated GoMock package.
package usertokenbanmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	core "github.com/assurrussa/goauth/internal/legacy/core"
)

// MockauthService is a mock of authService interface.
type MockauthService struct {
	ctrl     *gomock.Controller
	recorder *MockauthServiceMockRecorder
	isgomock struct{}
}

// MockauthServiceMockRecorder is the mock recorder for MockauthService.
type MockauthServiceMockRecorder struct {
	mock *MockauthService
}

// NewMockauthService creates a new mock instance.
func NewMockauthService(ctrl *gomock.Controller) *MockauthService {
	mock := &MockauthService{ctrl: ctrl}
	mock.recorder = &MockauthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthService) EXPECT() *MockauthServiceMockRecorder {
	return m.recorder
}

// BanToken mocks base method.
func (m *MockauthService) BanToken(ctx context.Context, subjectID core.SubjectID, tokenID int64, reason string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BanToken", ctx, subjectID, tokenID, reason)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BanToken indicates an expected call of BanToken.
func (mr *MockauthServiceMockRecorder) BanToken(ctx, subjectID, tokenID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BanToken", reflect.TypeOf((*MockauthService)(nil).BanToken), ctx, subjectID, tokenID, reason)
}
