// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/usecase_mock.gen.go -package=performpasswordresetmocks
//

// Package performpasswordresetmocks is a generated GoMock package.
package performpasswordresetmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockpasswordResetService is a mock of passwordResetService interface.
type MockpasswordResetService struct {
	ctrl     *gomock.Controller
	recorder *MockpasswordResetServiceMockRecorder
	isgomock struct{}
}

// MockpasswordResetServiceMockRecorder is the mock recorder for MockpasswordResetService.
type MockpasswordResetServiceMockRecorder struct {
	mock *MockpasswordResetService
}

// NewMockpasswordResetService creates a new mock instance.
func NewMockpasswordResetService(ctrl *gomock.Controller) *MockpasswordResetService {
	mock := &MockpasswordResetService{ctrl: ctrl}
	mock.recorder = &MockpasswordResetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpasswordResetService) EXPECT() *MockpasswordResetServiceMockRecorder {
	return m.recorder
}

// Perform mocks base method.
func (m *MockpasswordResetService) Perform(ctx context.Context, email, token, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Perform", ctx, email, token, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Perform indicates an expected call of Perform.
func (mr *MockpasswordResetServiceMockRecorder) Perform(ctx, email, token, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Perform", reflect.TypeOf((*MockpasswordResetService)(nil).Perform), ctx, email, token, password)
}
