// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service_mock.gen.go -package=rcucacheguardmocks
//

// Package rcucacheguardmocks is a generated GoMock package.
package rcucacheguardmocks

import (
	context "context"
	reflect "reflect"

	listallroles "github.com/assurrussa/goauth/domain/roles/usecases/query/list_all_roles"
	gomock "go.uber.org/mock/gomock"
)

// MockrolesAllUseCase is a mock of rolesAllUseCase interface.
type MockrolesAllUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockrolesAllUseCaseMockRecorder
	isgomock struct{}
}

// MockrolesAllUseCaseMockRecorder is the mock recorder for MockrolesAllUseCase.
type MockrolesAllUseCaseMockRecorder struct {
	mock *MockrolesAllUseCase
}

// NewMockrolesAllUseCase creates a new mock instance.
func NewMockrolesAllUseCase(ctrl *gomock.Controller) *MockrolesAllUseCase {
	mock := &MockrolesAllUseCase{ctrl: ctrl}
	mock.recorder = &MockrolesAllUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrolesAllUseCase) EXPECT() *MockrolesAllUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockrolesAllUseCase) Handle(ctx context.Context, req listallroles.Request) (listallroles.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(listallroles.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockrolesAllUseCaseMockRecorder) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockrolesAllUseCase)(nil).Handle), ctx, req)
}
