// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/goauth/usecases/command/request_password_reset (interfaces: passwordResetService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/usecase_mock.gen.go -package=requestpasswordresetmocks . passwordResetService
//

// Package requestpasswordresetmocks is a generated GoMock package.
package requestpasswordresetmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockpasswordResetService is a mock of passwordResetService interface.
type MockpasswordResetService struct {
	ctrl     *gomock.Controller
	recorder *MockpasswordResetServiceMockRecorder
	isgomock struct{}
}

// MockpasswordResetServiceMockRecorder is the mock recorder for MockpasswordResetService.
type MockpasswordResetServiceMockRecorder struct {
	mock *MockpasswordResetService
}

// NewMockpasswordResetService creates a new mock instance.
func NewMockpasswordResetService(ctrl *gomock.Controller) *MockpasswordResetService {
	mock := &MockpasswordResetService{ctrl: ctrl}
	mock.recorder = &MockpasswordResetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpasswordResetService) EXPECT() *MockpasswordResetServiceMockRecorder {
	return m.recorder
}

// Request mocks base method.
func (m *MockpasswordResetService) Request(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// Request indicates an expected call of Request.
func (mr *MockpasswordResetServiceMockRecorder) Request(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockpasswordResetService)(nil).Request), ctx, email)
}
