// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/goauth/usecases/command/user_logout (interfaces: authService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/usecase_mock.gen.go -package=userlogoutmocks . authService
//

// Package userlogoutmocks is a generated GoMock package.
package userlogoutmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	core "github.com/assurrussa/goauth/core"
)

// MockauthService is a mock of authService interface.
type MockauthService struct {
	ctrl     *gomock.Controller
	recorder *MockauthServiceMockRecorder
	isgomock struct{}
}

// MockauthServiceMockRecorder is the mock recorder for MockauthService.
type MockauthServiceMockRecorder struct {
	mock *MockauthService
}

// NewMockauthService creates a new mock instance.
func NewMockauthService(ctrl *gomock.Controller) *MockauthService {
	mock := &MockauthService{ctrl: ctrl}
	mock.recorder = &MockauthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthService) EXPECT() *MockauthServiceMockRecorder {
	return m.recorder
}

// DeleteRefreshToken mocks base method.
func (m *MockauthService) DeleteRefreshToken(ctx context.Context, subjectID core.SubjectID, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", ctx, subjectID, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockauthServiceMockRecorder) DeleteRefreshToken(ctx, subjectID, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockauthService)(nil).DeleteRefreshToken), ctx, subjectID, refreshToken)
}
