// Code generated by options-gen v0.55.3. DO NOT EDIT.

package confirmationcodeservice

import (
	fmt461e464ebed9 "fmt"
	"time"

	logger3 "github.com/assurrussa/goshared/pkg/logger"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"

	authcore "github.com/assurrussa/goauth/core"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	notificationService notificationService,
	userConfirmationCodeRepo userConfirmationCodeRepository,
	profiles authcore.ProfileLookup,
	projections authcore.ProfileProjectionWriter,
	subjects SubjectConfirmationStore,
	userConfirmationRepo userConfirmationRepository,
	logger logger3.Logger,
	outbox outboxPutter,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.codeExpiration, _ = time.ParseDuration("60m")
	o.maxAttempts = 5
	o.minResendInterval, _ = time.ParseDuration("60s")
	o.perHourLimit = 5
	o.perDayLimit = 10

	o.notificationService = notificationService
	o.userConfirmationCodeRepo = userConfirmationCodeRepo
	o.profiles = profiles
	o.projections = projections
	o.subjects = subjects
	o.userConfirmationRepo = userConfirmationRepo
	o.logger = logger
	o.outbox = outbox

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithCodeExpiration(opt time.Duration) OptOptionsSetter {
	return func(o *Options) { o.codeExpiration = opt }
}

func WithMaxAttempts(opt int) OptOptionsSetter {
	return func(o *Options) { o.maxAttempts = opt }
}

func WithMinResendInterval(opt time.Duration) OptOptionsSetter {
	return func(o *Options) { o.minResendInterval = opt }
}

func WithTelegramBotURL(opt string) OptOptionsSetter {
	return func(o *Options) { o.telegramBotURL = opt }
}

func WithPerHourLimit(opt int) OptOptionsSetter {
	return func(o *Options) { o.perHourLimit = opt }
}

func WithPerDayLimit(opt int) OptOptionsSetter {
	return func(o *Options) { o.perDayLimit = opt }
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("notificationService", _validate_Options_notificationService(o)))
	errs.Add(errors461e464ebed9.NewValidationError("userConfirmationCodeRepo", _validate_Options_userConfirmationCodeRepo(o)))
	errs.Add(errors461e464ebed9.NewValidationError("profiles", _validate_Options_profiles(o)))
	errs.Add(errors461e464ebed9.NewValidationError("projections", _validate_Options_projections(o)))
	errs.Add(errors461e464ebed9.NewValidationError("subjects", _validate_Options_subjects(o)))
	errs.Add(errors461e464ebed9.NewValidationError("userConfirmationRepo", _validate_Options_userConfirmationRepo(o)))
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	errs.Add(errors461e464ebed9.NewValidationError("outbox", _validate_Options_outbox(o)))
	return errs.AsError()
}

func _validate_Options_notificationService(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.notificationService, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `notificationService` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_userConfirmationCodeRepo(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.userConfirmationCodeRepo, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `userConfirmationCodeRepo` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_profiles(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.profiles, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `profiles` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_projections(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.projections, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `projections` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_subjects(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.subjects, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `subjects` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_userConfirmationRepo(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.userConfirmationRepo, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `userConfirmationRepo` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_outbox(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.outbox, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `outbox` did not pass the test: %w", err)
	}
	return nil
}
