// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/usecase_mock.gen.go -package=verifyconfirmationcodemocks
//

// Package verifyconfirmationcodemocks is a generated GoMock package.
package verifyconfirmationcodemocks

import (
	context "context"
	reflect "reflect"

	core "github.com/assurrussa/goauth/core"
	shared "github.com/assurrussa/goauth/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockconfirmationService is a mock of confirmationService interface.
type MockconfirmationService struct {
	ctrl     *gomock.Controller
	recorder *MockconfirmationServiceMockRecorder
	isgomock struct{}
}

// MockconfirmationServiceMockRecorder is the mock recorder for MockconfirmationService.
type MockconfirmationServiceMockRecorder struct {
	mock *MockconfirmationService
}

// NewMockconfirmationService creates a new mock instance.
func NewMockconfirmationService(ctrl *gomock.Controller) *MockconfirmationService {
	mock := &MockconfirmationService{ctrl: ctrl}
	mock.recorder = &MockconfirmationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconfirmationService) EXPECT() *MockconfirmationServiceMockRecorder {
	return m.recorder
}

// VerifyCode mocks base method.
func (m *MockconfirmationService) VerifyCode(ctx context.Context, subjectID core.SubjectID, code shared.ConfirmCode, codeType shared.ConfirmationType, purpose shared.ConfirmationPurpose) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyCode", ctx, subjectID, code, codeType, purpose)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyCode indicates an expected call of VerifyCode.
func (mr *MockconfirmationServiceMockRecorder) VerifyCode(ctx, subjectID, code, codeType, purpose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyCode", reflect.TypeOf((*MockconfirmationService)(nil).VerifyCode), ctx, subjectID, code, codeType, purpose)
}
