// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/usecase_mock.gen.go -package=sendconfirmationcodemocks
//

// Package sendconfirmationcodemocks is a generated GoMock package.
package sendconfirmationcodemocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	core "github.com/assurrussa/goauth/internal/legacy/core"
	shared "github.com/assurrussa/goauth/internal/legacy/shared"
)

// MockconfirmationService is a mock of confirmationService interface.
type MockconfirmationService struct {
	ctrl     *gomock.Controller
	recorder *MockconfirmationServiceMockRecorder
	isgomock struct{}
}

// MockconfirmationServiceMockRecorder is the mock recorder for MockconfirmationService.
type MockconfirmationServiceMockRecorder struct {
	mock *MockconfirmationService
}

// NewMockconfirmationService creates a new mock instance.
func NewMockconfirmationService(ctrl *gomock.Controller) *MockconfirmationService {
	mock := &MockconfirmationService{ctrl: ctrl}
	mock.recorder = &MockconfirmationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconfirmationService) EXPECT() *MockconfirmationServiceMockRecorder {
	return m.recorder
}

// GenerateAndSaveCode mocks base method.
func (m *MockconfirmationService) GenerateAndSaveCode(ctx context.Context, subjectID core.SubjectID, codeType shared.ConfirmationType, purpose shared.ConfirmationPurpose, targetConfirm string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAndSaveCode", ctx, subjectID, codeType, purpose, targetConfirm)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateAndSaveCode indicates an expected call of GenerateAndSaveCode.
func (mr *MockconfirmationServiceMockRecorder) GenerateAndSaveCode(ctx, subjectID, codeType, purpose, targetConfirm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAndSaveCode", reflect.TypeOf((*MockconfirmationService)(nil).GenerateAndSaveCode), ctx, subjectID, codeType, purpose, targetConfirm)
}

// MockprofileLookup is a mock of profileLookup interface.
type MockprofileLookup struct {
	ctrl     *gomock.Controller
	recorder *MockprofileLookupMockRecorder
	isgomock struct{}
}

// MockprofileLookupMockRecorder is the mock recorder for MockprofileLookup.
type MockprofileLookupMockRecorder struct {
	mock *MockprofileLookup
}

// NewMockprofileLookup creates a new mock instance.
func NewMockprofileLookup(ctrl *gomock.Controller) *MockprofileLookup {
	mock := &MockprofileLookup{ctrl: ctrl}
	mock.recorder = &MockprofileLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprofileLookup) EXPECT() *MockprofileLookupMockRecorder {
	return m.recorder
}

// GetBySubjectID mocks base method.
func (m *MockprofileLookup) GetBySubjectID(ctx context.Context, subjectID core.SubjectID) (core.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySubjectID", ctx, subjectID)
	ret0, _ := ret[0].(core.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySubjectID indicates an expected call of GetBySubjectID.
func (mr *MockprofileLookupMockRecorder) GetBySubjectID(ctx, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySubjectID", reflect.TypeOf((*MockprofileLookup)(nil).GetBySubjectID), ctx, subjectID)
}
