// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/usecase_mock.gen.go -package=userlogoutallmocks
//

// Package userlogoutallmocks is a generated GoMock package.
package userlogoutallmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	core "github.com/assurrussa/goauth/internal/legacy/core"
)

// MockauthService is a mock of authService interface.
type MockauthService struct {
	ctrl     *gomock.Controller
	recorder *MockauthServiceMockRecorder
	isgomock struct{}
}

// MockauthServiceMockRecorder is the mock recorder for MockauthService.
type MockauthServiceMockRecorder struct {
	mock *MockauthService
}

// NewMockauthService creates a new mock instance.
func NewMockauthService(ctrl *gomock.Controller) *MockauthService {
	mock := &MockauthService{ctrl: ctrl}
	mock.recorder = &MockauthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthService) EXPECT() *MockauthServiceMockRecorder {
	return m.recorder
}

// DeleteUserRefreshTokensExcept mocks base method.
func (m *MockauthService) DeleteUserRefreshTokensExcept(ctx context.Context, subjectID core.SubjectID, exceptToken string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserRefreshTokensExcept", ctx, subjectID, exceptToken)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUserRefreshTokensExcept indicates an expected call of DeleteUserRefreshTokensExcept.
func (mr *MockauthServiceMockRecorder) DeleteUserRefreshTokensExcept(ctx, subjectID, exceptToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserRefreshTokensExcept", reflect.TypeOf((*MockauthService)(nil).DeleteUserRefreshTokensExcept), ctx, subjectID, exceptToken)
}
