// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/usecase_mock.gen.go -package=getconfirmationinformationmocks
//

// Package getconfirmationinformationmocks is a generated GoMock package.
package getconfirmationinformationmocks

import (
	context "context"
	reflect "reflect"

	core "github.com/assurrussa/goauth/core"
	gomock "go.uber.org/mock/gomock"
)

// MockconfirmationCodeService is a mock of confirmationCodeService interface.
type MockconfirmationCodeService struct {
	ctrl     *gomock.Controller
	recorder *MockconfirmationCodeServiceMockRecorder
	isgomock struct{}
}

// MockconfirmationCodeServiceMockRecorder is the mock recorder for MockconfirmationCodeService.
type MockconfirmationCodeServiceMockRecorder struct {
	mock *MockconfirmationCodeService
}

// NewMockconfirmationCodeService creates a new mock instance.
func NewMockconfirmationCodeService(ctrl *gomock.Controller) *MockconfirmationCodeService {
	mock := &MockconfirmationCodeService{ctrl: ctrl}
	mock.recorder = &MockconfirmationCodeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockconfirmationCodeService) EXPECT() *MockconfirmationCodeServiceMockRecorder {
	return m.recorder
}

// GetConfirmationInfo mocks base method.
func (m *MockconfirmationCodeService) GetConfirmationInfo(ctx context.Context, subjectID core.SubjectID) (core.ConfirmationInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfirmationInfo", ctx, subjectID)
	ret0, _ := ret[0].(core.ConfirmationInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfirmationInfo indicates an expected call of GetConfirmationInfo.
func (mr *MockconfirmationCodeServiceMockRecorder) GetConfirmationInfo(ctx, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfirmationInfo", reflect.TypeOf((*MockconfirmationCodeService)(nil).GetConfirmationInfo), ctx, subjectID)
}
