// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/interfaces_mock.gen.go -package=coremocks
//

// Package coremocks is a generated GoMock package.
package coremocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"

	core "github.com/assurrussa/goauth/core"
)

// MockSubjectReader is a mock of SubjectReader interface.
type MockSubjectReader struct {
	ctrl     *gomock.Controller
	recorder *MockSubjectReaderMockRecorder
	isgomock struct{}
}

// MockSubjectReaderMockRecorder is the mock recorder for MockSubjectReader.
type MockSubjectReaderMockRecorder struct {
	mock *MockSubjectReader
}

// NewMockSubjectReader creates a new mock instance.
func NewMockSubjectReader(ctrl *gomock.Controller) *MockSubjectReader {
	mock := &MockSubjectReader{ctrl: ctrl}
	mock.recorder = &MockSubjectReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubjectReader) EXPECT() *MockSubjectReaderMockRecorder {
	return m.recorder
}

// GetByEmail mocks base method.
func (m *MockSubjectReader) GetByEmail(ctx context.Context, email string) (core.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(core.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockSubjectReaderMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockSubjectReader)(nil).GetByEmail), ctx, email)
}

// MockSubjectLookup is a mock of SubjectLookup interface.
type MockSubjectLookup struct {
	ctrl     *gomock.Controller
	recorder *MockSubjectLookupMockRecorder
	isgomock struct{}
}

// MockSubjectLookupMockRecorder is the mock recorder for MockSubjectLookup.
type MockSubjectLookupMockRecorder struct {
	mock *MockSubjectLookup
}

// NewMockSubjectLookup creates a new mock instance.
func NewMockSubjectLookup(ctrl *gomock.Controller) *MockSubjectLookup {
	mock := &MockSubjectLookup{ctrl: ctrl}
	mock.recorder = &MockSubjectLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubjectLookup) EXPECT() *MockSubjectLookupMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockSubjectLookup) GetByID(ctx context.Context, subjectID core.SubjectID) (core.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, subjectID)
	ret0, _ := ret[0].(core.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSubjectLookupMockRecorder) GetByID(ctx, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSubjectLookup)(nil).GetByID), ctx, subjectID)
}

// MockSubjectWriter is a mock of SubjectWriter interface.
type MockSubjectWriter struct {
	ctrl     *gomock.Controller
	recorder *MockSubjectWriterMockRecorder
	isgomock struct{}
}

// MockSubjectWriterMockRecorder is the mock recorder for MockSubjectWriter.
type MockSubjectWriterMockRecorder struct {
	mock *MockSubjectWriter
}

// NewMockSubjectWriter creates a new mock instance.
func NewMockSubjectWriter(ctrl *gomock.Controller) *MockSubjectWriter {
	mock := &MockSubjectWriter{ctrl: ctrl}
	mock.recorder = &MockSubjectWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubjectWriter) EXPECT() *MockSubjectWriterMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockSubjectWriter) CreateUser(ctx context.Context, subject core.Subject) (core.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, subject)
	ret0, _ := ret[0].(core.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockSubjectWriterMockRecorder) CreateUser(ctx, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockSubjectWriter)(nil).CreateUser), ctx, subject)
}

// UpdatePassword mocks base method.
func (m *MockSubjectWriter) UpdatePassword(ctx context.Context, subject core.Subject, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, subject, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockSubjectWriterMockRecorder) UpdatePassword(ctx, subject, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockSubjectWriter)(nil).UpdatePassword), ctx, subject, passwordHash)
}

// MockSubjectProfileWriter is a mock of SubjectProfileWriter interface.
type MockSubjectProfileWriter struct {
	ctrl     *gomock.Controller
	recorder *MockSubjectProfileWriterMockRecorder
	isgomock struct{}
}

// MockSubjectProfileWriterMockRecorder is the mock recorder for MockSubjectProfileWriter.
type MockSubjectProfileWriterMockRecorder struct {
	mock *MockSubjectProfileWriter
}

// NewMockSubjectProfileWriter creates a new mock instance.
func NewMockSubjectProfileWriter(ctrl *gomock.Controller) *MockSubjectProfileWriter {
	mock := &MockSubjectProfileWriter{ctrl: ctrl}
	mock.recorder = &MockSubjectProfileWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubjectProfileWriter) EXPECT() *MockSubjectProfileWriterMockRecorder {
	return m.recorder
}

// UpdateProfile mocks base method.
func (m *MockSubjectProfileWriter) UpdateProfile(ctx context.Context, subjectID core.SubjectID, patch core.SubjectProfilePatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, subjectID, patch)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockSubjectProfileWriterMockRecorder) UpdateProfile(ctx, subjectID, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockSubjectProfileWriter)(nil).UpdateProfile), ctx, subjectID, patch)
}

// MockSubjectCredentials is a mock of SubjectCredentials interface.
type MockSubjectCredentials struct {
	ctrl     *gomock.Controller
	recorder *MockSubjectCredentialsMockRecorder
	isgomock struct{}
}

// MockSubjectCredentialsMockRecorder is the mock recorder for MockSubjectCredentials.
type MockSubjectCredentialsMockRecorder struct {
	mock *MockSubjectCredentials
}

// NewMockSubjectCredentials creates a new mock instance.
func NewMockSubjectCredentials(ctrl *gomock.Controller) *MockSubjectCredentials {
	mock := &MockSubjectCredentials{ctrl: ctrl}
	mock.recorder = &MockSubjectCredentialsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubjectCredentials) EXPECT() *MockSubjectCredentialsMockRecorder {
	return m.recorder
}

// GetPasswordHash mocks base method.
func (m *MockSubjectCredentials) GetPasswordHash(ctx context.Context, subject core.Subject) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasswordHash", ctx, subject)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasswordHash indicates an expected call of GetPasswordHash.
func (mr *MockSubjectCredentialsMockRecorder) GetPasswordHash(ctx, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasswordHash", reflect.TypeOf((*MockSubjectCredentials)(nil).GetPasswordHash), ctx, subject)
}

// MockRefreshTokenStore is a mock of RefreshTokenStore interface.
type MockRefreshTokenStore struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenStoreMockRecorder
	isgomock struct{}
}

// MockRefreshTokenStoreMockRecorder is the mock recorder for MockRefreshTokenStore.
type MockRefreshTokenStoreMockRecorder struct {
	mock *MockRefreshTokenStore
}

// NewMockRefreshTokenStore creates a new mock instance.
func NewMockRefreshTokenStore(ctrl *gomock.Controller) *MockRefreshTokenStore {
	mock := &MockRefreshTokenStore{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenStore) EXPECT() *MockRefreshTokenStoreMockRecorder {
	return m.recorder
}

// Ban mocks base method.
func (m *MockRefreshTokenStore) Ban(ctx context.Context, subjectID core.SubjectID, sessionID int64, reason string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ban", ctx, subjectID, sessionID, reason)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ban indicates an expected call of Ban.
func (mr *MockRefreshTokenStoreMockRecorder) Ban(ctx, subjectID, sessionID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ban", reflect.TypeOf((*MockRefreshTokenStore)(nil).Ban), ctx, subjectID, sessionID, reason)
}

// Delete mocks base method.
func (m *MockRefreshTokenStore) Delete(ctx context.Context, subjectID core.SubjectID, token string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, subjectID, token)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRefreshTokenStoreMockRecorder) Delete(ctx, subjectID, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRefreshTokenStore)(nil).Delete), ctx, subjectID, token)
}

// DeleteAll mocks base method.
func (m *MockRefreshTokenStore) DeleteAll(ctx context.Context, subjectID core.SubjectID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", ctx, subjectID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockRefreshTokenStoreMockRecorder) DeleteAll(ctx, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockRefreshTokenStore)(nil).DeleteAll), ctx, subjectID)
}

// DeleteAllExcept mocks base method.
func (m *MockRefreshTokenStore) DeleteAllExcept(ctx context.Context, subjectID core.SubjectID, keepToken string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllExcept", ctx, subjectID, keepToken)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAllExcept indicates an expected call of DeleteAllExcept.
func (mr *MockRefreshTokenStoreMockRecorder) DeleteAllExcept(ctx, subjectID, keepToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllExcept", reflect.TypeOf((*MockRefreshTokenStore)(nil).DeleteAllExcept), ctx, subjectID, keepToken)
}

// DeleteBySessionID mocks base method.
func (m *MockRefreshTokenStore) DeleteBySessionID(ctx context.Context, subjectID core.SubjectID, sessionID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBySessionID", ctx, subjectID, sessionID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBySessionID indicates an expected call of DeleteBySessionID.
func (mr *MockRefreshTokenStoreMockRecorder) DeleteBySessionID(ctx, subjectID, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBySessionID", reflect.TypeOf((*MockRefreshTokenStore)(nil).DeleteBySessionID), ctx, subjectID, sessionID)
}

// Get mocks base method.
func (m *MockRefreshTokenStore) Get(ctx context.Context, token string) (core.AuthSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, token)
	ret0, _ := ret[0].(core.AuthSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRefreshTokenStoreMockRecorder) Get(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRefreshTokenStore)(nil).Get), ctx, token)
}

// GetBySessionID mocks base method.
func (m *MockRefreshTokenStore) GetBySessionID(ctx context.Context, sessionID int64) (core.AuthSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySessionID", ctx, sessionID)
	ret0, _ := ret[0].(core.AuthSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySessionID indicates an expected call of GetBySessionID.
func (mr *MockRefreshTokenStoreMockRecorder) GetBySessionID(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySessionID", reflect.TypeOf((*MockRefreshTokenStore)(nil).GetBySessionID), ctx, sessionID)
}

// IsBanned mocks base method.
func (m *MockRefreshTokenStore) IsBanned(ctx context.Context, token string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBanned", ctx, token)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsBanned indicates an expected call of IsBanned.
func (mr *MockRefreshTokenStoreMockRecorder) IsBanned(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBanned", reflect.TypeOf((*MockRefreshTokenStore)(nil).IsBanned), ctx, token)
}

// ListBySubject mocks base method.
func (m *MockRefreshTokenStore) ListBySubject(ctx context.Context, subjectID core.SubjectID) ([]core.AuthSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySubject", ctx, subjectID)
	ret0, _ := ret[0].([]core.AuthSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBySubject indicates an expected call of ListBySubject.
func (mr *MockRefreshTokenStoreMockRecorder) ListBySubject(ctx, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySubject", reflect.TypeOf((*MockRefreshTokenStore)(nil).ListBySubject), ctx, subjectID)
}

// Save mocks base method.
func (m *MockRefreshTokenStore) Save(ctx context.Context, session core.AuthSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRefreshTokenStoreMockRecorder) Save(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRefreshTokenStore)(nil).Save), ctx, session)
}

// Unban mocks base method.
func (m *MockRefreshTokenStore) Unban(ctx context.Context, subjectID core.SubjectID, sessionID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unban", ctx, subjectID, sessionID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unban indicates an expected call of Unban.
func (mr *MockRefreshTokenStoreMockRecorder) Unban(ctx, subjectID, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unban", reflect.TypeOf((*MockRefreshTokenStore)(nil).Unban), ctx, subjectID, sessionID)
}

// MockPasswordResetStore is a mock of PasswordResetStore interface.
type MockPasswordResetStore struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordResetStoreMockRecorder
	isgomock struct{}
}

// MockPasswordResetStoreMockRecorder is the mock recorder for MockPasswordResetStore.
type MockPasswordResetStoreMockRecorder struct {
	mock *MockPasswordResetStore
}

// NewMockPasswordResetStore creates a new mock instance.
func NewMockPasswordResetStore(ctrl *gomock.Controller) *MockPasswordResetStore {
	mock := &MockPasswordResetStore{ctrl: ctrl}
	mock.recorder = &MockPasswordResetStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordResetStore) EXPECT() *MockPasswordResetStoreMockRecorder {
	return m.recorder
}

// DeleteByEmail mocks base method.
func (m *MockPasswordResetStore) DeleteByEmail(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByEmail", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByEmail indicates an expected call of DeleteByEmail.
func (mr *MockPasswordResetStoreMockRecorder) DeleteByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByEmail", reflect.TypeOf((*MockPasswordResetStore)(nil).DeleteByEmail), ctx, email)
}

// GetByEmail mocks base method.
func (m *MockPasswordResetStore) GetByEmail(ctx context.Context, email string) (core.PasswordResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(core.PasswordResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockPasswordResetStoreMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockPasswordResetStore)(nil).GetByEmail), ctx, email)
}

// Upsert mocks base method.
func (m *MockPasswordResetStore) Upsert(ctx context.Context, token core.PasswordResetToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockPasswordResetStoreMockRecorder) Upsert(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockPasswordResetStore)(nil).Upsert), ctx, token)
}

// MockConfirmationStore is a mock of ConfirmationStore interface.
type MockConfirmationStore struct {
	ctrl     *gomock.Controller
	recorder *MockConfirmationStoreMockRecorder
	isgomock struct{}
}

// MockConfirmationStoreMockRecorder is the mock recorder for MockConfirmationStore.
type MockConfirmationStoreMockRecorder struct {
	mock *MockConfirmationStore
}

// NewMockConfirmationStore creates a new mock instance.
func NewMockConfirmationStore(ctrl *gomock.Controller) *MockConfirmationStore {
	mock := &MockConfirmationStore{ctrl: ctrl}
	mock.recorder = &MockConfirmationStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfirmationStore) EXPECT() *MockConfirmationStoreMockRecorder {
	return m.recorder
}

// ConfirmCode mocks base method.
func (m *MockConfirmationStore) ConfirmCode(ctx context.Context, subjectID core.SubjectID, purpose, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmCode", ctx, subjectID, purpose, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmCode indicates an expected call of ConfirmCode.
func (mr *MockConfirmationStoreMockRecorder) ConfirmCode(ctx, subjectID, purpose, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmCode", reflect.TypeOf((*MockConfirmationStore)(nil).ConfirmCode), ctx, subjectID, purpose, code)
}

// SaveCode mocks base method.
func (m *MockConfirmationStore) SaveCode(ctx context.Context, subjectID core.SubjectID, purpose, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCode", ctx, subjectID, purpose, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCode indicates an expected call of SaveCode.
func (mr *MockConfirmationStoreMockRecorder) SaveCode(ctx, subjectID, purpose, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCode", reflect.TypeOf((*MockConfirmationStore)(nil).SaveCode), ctx, subjectID, purpose, code)
}

// MockPasswordHasher is a mock of PasswordHasher interface.
type MockPasswordHasher struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordHasherMockRecorder
	isgomock struct{}
}

// MockPasswordHasherMockRecorder is the mock recorder for MockPasswordHasher.
type MockPasswordHasherMockRecorder struct {
	mock *MockPasswordHasher
}

// NewMockPasswordHasher creates a new mock instance.
func NewMockPasswordHasher(ctrl *gomock.Controller) *MockPasswordHasher {
	mock := &MockPasswordHasher{ctrl: ctrl}
	mock.recorder = &MockPasswordHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordHasher) EXPECT() *MockPasswordHasherMockRecorder {
	return m.recorder
}

// CompareHash mocks base method.
func (m *MockPasswordHasher) CompareHash(passwordHash, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompareHash", passwordHash, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompareHash indicates an expected call of CompareHash.
func (mr *MockPasswordHasherMockRecorder) CompareHash(passwordHash, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompareHash", reflect.TypeOf((*MockPasswordHasher)(nil).CompareHash), passwordHash, password)
}

// GenerateHash mocks base method.
func (m *MockPasswordHasher) GenerateHash(password string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateHash", password)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateHash indicates an expected call of GenerateHash.
func (mr *MockPasswordHasherMockRecorder) GenerateHash(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateHash", reflect.TypeOf((*MockPasswordHasher)(nil).GenerateHash), password)
}

// MockTokenIssuer is a mock of TokenIssuer interface.
type MockTokenIssuer struct {
	ctrl     *gomock.Controller
	recorder *MockTokenIssuerMockRecorder
	isgomock struct{}
}

// MockTokenIssuerMockRecorder is the mock recorder for MockTokenIssuer.
type MockTokenIssuerMockRecorder struct {
	mock *MockTokenIssuer
}

// NewMockTokenIssuer creates a new mock instance.
func NewMockTokenIssuer(ctrl *gomock.Controller) *MockTokenIssuer {
	mock := &MockTokenIssuer{ctrl: ctrl}
	mock.recorder = &MockTokenIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenIssuer) EXPECT() *MockTokenIssuerMockRecorder {
	return m.recorder
}

// GenerateTokenPair mocks base method.
func (m *MockTokenIssuer) GenerateTokenPair(subject core.Subject) (*core.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokenPair", subject)
	ret0, _ := ret[0].(*core.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTokenPair indicates an expected call of GenerateTokenPair.
func (mr *MockTokenIssuerMockRecorder) GenerateTokenPair(subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokenPair", reflect.TypeOf((*MockTokenIssuer)(nil).GenerateTokenPair), subject)
}

// MockSessionIssuer is a mock of SessionIssuer interface.
type MockSessionIssuer struct {
	ctrl     *gomock.Controller
	recorder *MockSessionIssuerMockRecorder
	isgomock struct{}
}

// MockSessionIssuerMockRecorder is the mock recorder for MockSessionIssuer.
type MockSessionIssuerMockRecorder struct {
	mock *MockSessionIssuer
}

// NewMockSessionIssuer creates a new mock instance.
func NewMockSessionIssuer(ctrl *gomock.Controller) *MockSessionIssuer {
	mock := &MockSessionIssuer{ctrl: ctrl}
	mock.recorder = &MockSessionIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionIssuer) EXPECT() *MockSessionIssuerMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockSessionIssuer) CreateSession(ctx context.Context, subject core.Subject) (*core.AuthSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, subject)
	ret0, _ := ret[0].(*core.AuthSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionIssuerMockRecorder) CreateSession(ctx, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSessionIssuer)(nil).CreateSession), ctx, subject)
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// RunInTx mocks base method.
func (m *MockTxManager) RunInTx(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MockTxManagerMockRecorder) RunInTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*MockTxManager)(nil).RunInTx), ctx, fn)
}

// MockProfileLookup is a mock of ProfileLookup interface.
type MockProfileLookup struct {
	ctrl     *gomock.Controller
	recorder *MockProfileLookupMockRecorder
	isgomock struct{}
}

// MockProfileLookupMockRecorder is the mock recorder for MockProfileLookup.
type MockProfileLookupMockRecorder struct {
	mock *MockProfileLookup
}

// NewMockProfileLookup creates a new mock instance.
func NewMockProfileLookup(ctrl *gomock.Controller) *MockProfileLookup {
	mock := &MockProfileLookup{ctrl: ctrl}
	mock.recorder = &MockProfileLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileLookup) EXPECT() *MockProfileLookupMockRecorder {
	return m.recorder
}

// GetBySubjectID mocks base method.
func (m *MockProfileLookup) GetBySubjectID(ctx context.Context, subjectID core.SubjectID) (core.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySubjectID", ctx, subjectID)
	ret0, _ := ret[0].(core.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySubjectID indicates an expected call of GetBySubjectID.
func (mr *MockProfileLookupMockRecorder) GetBySubjectID(ctx, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySubjectID", reflect.TypeOf((*MockProfileLookup)(nil).GetBySubjectID), ctx, subjectID)
}

// MockProfileProvisioner is a mock of ProfileProvisioner interface.
type MockProfileProvisioner struct {
	ctrl     *gomock.Controller
	recorder *MockProfileProvisionerMockRecorder
	isgomock struct{}
}

// MockProfileProvisionerMockRecorder is the mock recorder for MockProfileProvisioner.
type MockProfileProvisionerMockRecorder struct {
	mock *MockProfileProvisioner
}

// NewMockProfileProvisioner creates a new mock instance.
func NewMockProfileProvisioner(ctrl *gomock.Controller) *MockProfileProvisioner {
	mock := &MockProfileProvisioner{ctrl: ctrl}
	mock.recorder = &MockProfileProvisionerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileProvisioner) EXPECT() *MockProfileProvisionerMockRecorder {
	return m.recorder
}

// ProvisionForSubject mocks base method.
func (m *MockProfileProvisioner) ProvisionForSubject(ctx context.Context, subject core.Subject) (core.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProvisionForSubject", ctx, subject)
	ret0, _ := ret[0].(core.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProvisionForSubject indicates an expected call of ProvisionForSubject.
func (mr *MockProfileProvisionerMockRecorder) ProvisionForSubject(ctx, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProvisionForSubject", reflect.TypeOf((*MockProfileProvisioner)(nil).ProvisionForSubject), ctx, subject)
}

// MockProfileProjectionWriter is a mock of ProfileProjectionWriter interface.
type MockProfileProjectionWriter struct {
	ctrl     *gomock.Controller
	recorder *MockProfileProjectionWriterMockRecorder
	isgomock struct{}
}

// MockProfileProjectionWriterMockRecorder is the mock recorder for MockProfileProjectionWriter.
type MockProfileProjectionWriterMockRecorder struct {
	mock *MockProfileProjectionWriter
}

// NewMockProfileProjectionWriter creates a new mock instance.
func NewMockProfileProjectionWriter(ctrl *gomock.Controller) *MockProfileProjectionWriter {
	mock := &MockProfileProjectionWriter{ctrl: ctrl}
	mock.recorder = &MockProfileProjectionWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileProjectionWriter) EXPECT() *MockProfileProjectionWriterMockRecorder {
	return m.recorder
}

// MarkPhoneConfirmed mocks base method.
func (m *MockProfileProjectionWriter) MarkPhoneConfirmed(ctx context.Context, subjectID core.SubjectID, confirmedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPhoneConfirmed", ctx, subjectID, confirmedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPhoneConfirmed indicates an expected call of MarkPhoneConfirmed.
func (mr *MockProfileProjectionWriterMockRecorder) MarkPhoneConfirmed(ctx, subjectID, confirmedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPhoneConfirmed", reflect.TypeOf((*MockProfileProjectionWriter)(nil).MarkPhoneConfirmed), ctx, subjectID, confirmedAt)
}
